### ISSUE TITLE
Multi-run simulations

### ISSUE THREAD

**Issue by yjaguilara** [fabern/LWFBrook90.jl#87]
Hi, I have been using Brook90.jl to run individual simulations and perform hydrologic analysis of soil water moisture and groundwater storage.
I would like to be able to run several simulations varying the values of some parameters in order to perform sensitivity analysis. Is there any method or function that allows me to run multiple simulations, only varying the values of certain parameters within certain established ranges?

Since I need to do more than 1000 simulations, it is tedious to have to prepare the csv for each of the simulations and run them individually; therefore any guide or help to be able to do multirunning would be super useful.

Thank you in advance for your response and help.

**Comment by fabern** [comment]
Hi Juliana,

Yes there is. You can do this with `remakeSPAC()` (documentation under: https://fabern.github.io/LWFBrook90.jl/stable/function-docs/#LWFBrook90.remakeSPAC-Tuple%7BDiscretizedSPAC%7D)

Sorry, for my brevity. I currently don‘t have access to a computer. So I can‘t provide you an example script. Let me know if this is enough to get you started…
The function call depends on which parameters you want to vary. Do you already know which parameters these are?

Best regards, Fabian
